-- CREATE TABLE IF NOT EXISTS TABLENAME (
--   id SERIAL PRIMARY KEY,
--   created_at TIMESTAMP NOT NULL DEFAULT NOW(),
--   updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
--   deleted_at TIMESTAMP
-- );

-- CREATE OR REPLACE FUNCTION TABLENAME_update_timestamp()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   NEW.updated_at = NOW();
--   RETURN NEW;
-- END;
-- $$ language 'plpgsql';

-- CREATE TRIGGER TABLENAME_update_timestamp
-- BEFORE UPDATE ON TABLENAME
-- FOR EACH ROW EXECUTE PROCEDURE TABLENAME_update_timestamp();

-- CREATE TRIGGER TABLENAME_update_timestamp
-- BEFORE INSERT ON TABLENAME
-- FOR EACH ROW EXECUTE PROCEDURE TABLENAME_update_timestamp();

-- CREATE TRIGGER TABLENAME_update_timestamp
-- BEFORE DELETE ON TABLENAME
-- FOR EACH ROW EXECUTE PROCEDURE TABLENAME_update_timestamp();

